baseURL = "https://aspr-works.top/"
title = "nova+z's sounds & logs"
description = "nova+z Official Website — home of the independent project Astral Parade, featuring music and blog posts."
languageCode = "zh-CN"
timeZone = "Asia/Shanghai"
enableRobotsTXT = true

[params]
  email = "novaxz@aspr-works.top"
  social = [
    "https://x.com/novaxz_nobasu",
    "https://soundcloud.com/novaxz_aspr",
    "https://novaxz.bandcamp.com/",
    "https://www.youtube.com/@novaxz_aspr",
    "https://space.bilibili.com/31785876",
    "https://music.163.com/#/artist?id=52170515",
  ]

[build]
  [build.buildStats]
    enable = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Discography"
    url = "/discography/"
    weight = 20

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[taxonomies]
  category = "category"
  year = "year"
  tag = "tag"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4